// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $AddToCartBuyTogether from "./islands/AddToCartBuyTogether.tsx";
import * as $ColorDetails from "./islands/ColorDetails.tsx";
import * as $ColorPaletteInteractiveTabs from "./islands/ColorPaletteInteractiveTabs.tsx";
import * as $ColorQuiz from "./islands/ColorQuiz.tsx";
import * as $ColorVariantSelector from "./islands/ColorVariantSelector.tsx";
import * as $FaqInstitutionalInteractive from "./islands/FaqInstitutionalInteractive.tsx";
import * as $FilterRangePrice from "./islands/FilterRangePrice.tsx";
import * as $Filters from "./islands/Filters.tsx";
import * as $Gallery from "./islands/Gallery.tsx";
import * as $InstitutionalMobileMenu from "./islands/InstitutionalMobileMenu.tsx";
import * as $KitAddToCart from "./islands/KitAddToCart.tsx";
import * as $KonfidencyReviews from "./islands/KonfidencyReviews.tsx";
import * as $Newsletter from "./islands/Newsletter.tsx";
import * as $ProductCardColorSelector from "./islands/ProductCardColorSelector.tsx";
import * as $ProductTipsVideo from "./islands/ProductTipsVideo.tsx";
import * as $QuantitySelectorInteractive from "./islands/QuantitySelectorInteractive.tsx";
import * as $QuantitySelectorMinicartInteractive from "./islands/QuantitySelectorMinicartInteractive.tsx";
import * as $ScrollHeader from "./islands/ScrollHeader.tsx";
import * as $SearchError from "./islands/SearchError.tsx";
import * as $ShelfColorModal from "./islands/ShelfColorModal.tsx";
import * as $ShopTheLookModal from "./islands/ShopTheLookModal.tsx";
import * as $SliderJS from "./islands/SliderJS.tsx";
import * as $TabbedSliderJS from "./islands/TabbedSliderJS.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
  },
  islands: {
    "./islands/AddToCartBuyTogether.tsx": $AddToCartBuyTogether,
    "./islands/ColorDetails.tsx": $ColorDetails,
    "./islands/ColorPaletteInteractiveTabs.tsx": $ColorPaletteInteractiveTabs,
    "./islands/ColorQuiz.tsx": $ColorQuiz,
    "./islands/ColorVariantSelector.tsx": $ColorVariantSelector,
    "./islands/FaqInstitutionalInteractive.tsx": $FaqInstitutionalInteractive,
    "./islands/FilterRangePrice.tsx": $FilterRangePrice,
    "./islands/Filters.tsx": $Filters,
    "./islands/Gallery.tsx": $Gallery,
    "./islands/InstitutionalMobileMenu.tsx": $InstitutionalMobileMenu,
    "./islands/KitAddToCart.tsx": $KitAddToCart,
    "./islands/KonfidencyReviews.tsx": $KonfidencyReviews,
    "./islands/Newsletter.tsx": $Newsletter,
    "./islands/ProductCardColorSelector.tsx": $ProductCardColorSelector,
    "./islands/ProductTipsVideo.tsx": $ProductTipsVideo,
    "./islands/QuantitySelectorInteractive.tsx": $QuantitySelectorInteractive,
    "./islands/QuantitySelectorMinicartInteractive.tsx":
      $QuantitySelectorMinicartInteractive,
    "./islands/ScrollHeader.tsx": $ScrollHeader,
    "./islands/SearchError.tsx": $SearchError,
    "./islands/ShelfColorModal.tsx": $ShelfColorModal,
    "./islands/ShopTheLookModal.tsx": $ShopTheLookModal,
    "./islands/SliderJS.tsx": $SliderJS,
    "./islands/TabbedSliderJS.tsx": $TabbedSliderJS,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
