// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/minicart/submit.ts";
import * as $$$$$$$$$1 from "./actions/newsletter/submit.ts";
import * as $$$$$$$$$2 from "./actions/wishlist/submit.ts";
import * as $$$$$$$$$$$0 from "./apps/deco/analytics.ts";
import * as $$$$$$$$$$$1 from "./apps/deco/htmx.ts";
import * as $$$$$$$$$$$2 from "./apps/deco/konfidency.ts";
import * as $$$$$$$$$$$3 from "./apps/deco/vtex.ts";
import * as $$$$$$$$$$$4 from "./apps/site.ts";
import * as $$$0 from "./loaders/availableIcons.ts";
import * as $$$1 from "./loaders/icons.ts";
import * as $$$2 from "./loaders/konfidency/productDetailsPage.ts";
import * as $$$3 from "./loaders/minicart.ts";
import * as $$$4 from "./loaders/product/buyTogetherSuggestions.ts";
import * as $$$5 from "./loaders/user.ts";
import * as $$$6 from "./loaders/wishlist.ts";
import * as $$$$$$0 from "./sections/Animation/Animation.tsx";
import * as $$$$$$1 from "./sections/Category/CategoryBanner.tsx";
import * as $$$$$$2 from "./sections/Category/CategoryGrid.tsx";
import * as $$$$$$3 from "./sections/Category/MinicartCategories.tsx";
import * as $$$$$$4 from "./sections/Category/ProductCategories.tsx";
import * as $$$$$$5 from "./sections/Component.tsx";
import * as $$$$$$6 from "./sections/Content/BannerInstitutional.tsx";
import * as $$$$$$7 from "./sections/Content/Faq.tsx";
import * as $$$$$$8 from "./sections/Content/Hero.tsx";
import * as $$$$$$9 from "./sections/Content/InstitutionalMain.tsx";
import * as $$$$$$10 from "./sections/Content/Intro.tsx";
import * as $$$$$$11 from "./sections/Content/Logos.tsx";
import * as $$$$$$12 from "./sections/Content/SeoText.tsx";
import * as $$$$$$13 from "./sections/Footer/Footer.tsx";
import * as $$$$$$14 from "./sections/Footer/Newsletter.tsx";
import * as $$$$$$15 from "./sections/Header/Header.tsx";
import * as $$$$$$16 from "./sections/Images/Banner.tsx";
import * as $$$$$$17 from "./sections/Images/BannerSlider.tsx";
import * as $$$$$$18 from "./sections/Images/CardSlider.tsx";
import * as $$$$$$19 from "./sections/Images/Carousel.tsx";
import * as $$$$$$20 from "./sections/Images/ImageGallery.tsx";
import * as $$$$$$21 from "./sections/Images/ImageHome.tsx";
import * as $$$$$$22 from "./sections/Images/Minibanners.tsx";
import * as $$$$$$24 from "./sections/Images/ShoppableBanner.tsx";
import * as $$$$$$23 from "./sections/Images/ShopTheLook.tsx";
import * as $$$$$$25 from "./sections/Institutional/Cardinstitutional.tsx";
import * as $$$$$$26 from "./sections/Institutional/Faqinstitutional.tsx";
import * as $$$$$$27 from "./sections/Institutional/Imagecardinstitutional.tsx";
import * as $$$$$$28 from "./sections/Institutional/Imageicon2institutional.tsx";
import * as $$$$$$33 from "./sections/Institutional/imageiconinstitucionla.tsx";
import * as $$$$$$29 from "./sections/Institutional/Lipimageinstitutional.tsx";
import * as $$$$$$30 from "./sections/Institutional/Newgiftinstitutional.tsx";
import * as $$$$$$34 from "./sections/Institutional/quiosquesinstitutional.tsx";
import * as $$$$$$31 from "./sections/Institutional/Quiosquesinstitutional.tsx";
import * as $$$$$$32 from "./sections/Institutional/Wherefindinstitutional.tsx";
import * as $$$$$$35 from "./sections/Links/LinkTree.tsx";
import * as $$$$$$36 from "./sections/Miscellaneous/Benefits.tsx";
import * as $$$$$$37 from "./sections/Miscellaneous/CampaignTimer.tsx";
import * as $$$$$$38 from "./sections/Miscellaneous/CookieConsent.tsx";
import * as $$$$$$39 from "./sections/Newsletter/Newsletter.tsx";
import * as $$$$$$40 from "./sections/Product/ProductBuyTogether.tsx";
import * as $$$$$$41 from "./sections/Product/ProductColors.tsx";
import * as $$$$$$42 from "./sections/Product/ProductComposition.tsx";
import * as $$$$$$43 from "./sections/Product/ProductDescription.tsx";
import * as $$$$$$44 from "./sections/Product/ProductDetails.tsx";
import * as $$$$$$45 from "./sections/Product/ProductFaq.tsx";
import * as $$$$$$46 from "./sections/Product/ProductReviews.tsx";
import * as $$$$$$47 from "./sections/Product/ProductShelf.tsx";
import * as $$$$$$48 from "./sections/Product/ProductShelfSimilars.tsx";
import * as $$$$$$49 from "./sections/Product/ProductShelfTabbed.tsx";
import * as $$$$$$50 from "./sections/Product/ProductTips.tsx";
import * as $$$$$$51 from "./sections/Product/SearchResult.tsx";
import * as $$$$$$52 from "./sections/Product/ShelfWithImage.tsx";
import * as $$$$$$53 from "./sections/Product/TabbedProductSlider.tsx";
import * as $$$$$$54 from "./sections/Product/Wishlist.tsx";
import * as $$$$$$55 from "./sections/SearchError/SearchErrorBreadcrumb.tsx";
import * as $$$$$$56 from "./sections/Session.tsx";
import * as $$$$$$57 from "./sections/Social/InstagramFeed.tsx";
import * as $$$$$$58 from "./sections/Social/InstagramPosts.tsx";
import * as $$$$$$59 from "./sections/Social/WhatsApp.tsx";
import * as $$$$$$60 from "./sections/Theme/Theme.tsx";

const manifest = {
  "loaders": {
    "site/loaders/availableIcons.ts": $$$0,
    "site/loaders/icons.ts": $$$1,
    "site/loaders/konfidency/productDetailsPage.ts": $$$2,
    "site/loaders/minicart.ts": $$$3,
    "site/loaders/product/buyTogetherSuggestions.ts": $$$4,
    "site/loaders/user.ts": $$$5,
    "site/loaders/wishlist.ts": $$$6,
  },
  "sections": {
    "site/sections/Animation/Animation.tsx": $$$$$$0,
    "site/sections/Category/CategoryBanner.tsx": $$$$$$1,
    "site/sections/Category/CategoryGrid.tsx": $$$$$$2,
    "site/sections/Category/MinicartCategories.tsx": $$$$$$3,
    "site/sections/Category/ProductCategories.tsx": $$$$$$4,
    "site/sections/Component.tsx": $$$$$$5,
    "site/sections/Content/BannerInstitutional.tsx": $$$$$$6,
    "site/sections/Content/Faq.tsx": $$$$$$7,
    "site/sections/Content/Hero.tsx": $$$$$$8,
    "site/sections/Content/InstitutionalMain.tsx": $$$$$$9,
    "site/sections/Content/Intro.tsx": $$$$$$10,
    "site/sections/Content/Logos.tsx": $$$$$$11,
    "site/sections/Content/SeoText.tsx": $$$$$$12,
    "site/sections/Footer/Footer.tsx": $$$$$$13,
    "site/sections/Footer/Newsletter.tsx": $$$$$$14,
    "site/sections/Header/Header.tsx": $$$$$$15,
    "site/sections/Images/Banner.tsx": $$$$$$16,
    "site/sections/Images/BannerSlider.tsx": $$$$$$17,
    "site/sections/Images/CardSlider.tsx": $$$$$$18,
    "site/sections/Images/Carousel.tsx": $$$$$$19,
    "site/sections/Images/ImageGallery.tsx": $$$$$$20,
    "site/sections/Images/ImageHome.tsx": $$$$$$21,
    "site/sections/Images/Minibanners.tsx": $$$$$$22,
    "site/sections/Images/ShoppableBanner.tsx": $$$$$$24,
    "site/sections/Images/ShopTheLook.tsx": $$$$$$23,
    "site/sections/Institutional/Cardinstitutional.tsx": $$$$$$25,
    "site/sections/Institutional/Faqinstitutional.tsx": $$$$$$26,
    "site/sections/Institutional/Imagecardinstitutional.tsx": $$$$$$27,
    "site/sections/Institutional/Imageicon2institutional.tsx": $$$$$$28,
    "site/sections/Institutional/imageiconinstitucionla.tsx": $$$$$$33,
    "site/sections/Institutional/Lipimageinstitutional.tsx": $$$$$$29,
    "site/sections/Institutional/Newgiftinstitutional.tsx": $$$$$$30,
    "site/sections/Institutional/quiosquesinstitutional.tsx": $$$$$$34,
    "site/sections/Institutional/Quiosquesinstitutional.tsx": $$$$$$31,
    "site/sections/Institutional/Wherefindinstitutional.tsx": $$$$$$32,
    "site/sections/Links/LinkTree.tsx": $$$$$$35,
    "site/sections/Miscellaneous/Benefits.tsx": $$$$$$36,
    "site/sections/Miscellaneous/CampaignTimer.tsx": $$$$$$37,
    "site/sections/Miscellaneous/CookieConsent.tsx": $$$$$$38,
    "site/sections/Newsletter/Newsletter.tsx": $$$$$$39,
    "site/sections/Product/ProductBuyTogether.tsx": $$$$$$40,
    "site/sections/Product/ProductColors.tsx": $$$$$$41,
    "site/sections/Product/ProductComposition.tsx": $$$$$$42,
    "site/sections/Product/ProductDescription.tsx": $$$$$$43,
    "site/sections/Product/ProductDetails.tsx": $$$$$$44,
    "site/sections/Product/ProductFaq.tsx": $$$$$$45,
    "site/sections/Product/ProductReviews.tsx": $$$$$$46,
    "site/sections/Product/ProductShelf.tsx": $$$$$$47,
    "site/sections/Product/ProductShelfSimilars.tsx": $$$$$$48,
    "site/sections/Product/ProductShelfTabbed.tsx": $$$$$$49,
    "site/sections/Product/ProductTips.tsx": $$$$$$50,
    "site/sections/Product/SearchResult.tsx": $$$$$$51,
    "site/sections/Product/ShelfWithImage.tsx": $$$$$$52,
    "site/sections/Product/TabbedProductSlider.tsx": $$$$$$53,
    "site/sections/Product/Wishlist.tsx": $$$$$$54,
    "site/sections/SearchError/SearchErrorBreadcrumb.tsx": $$$$$$55,
    "site/sections/Session.tsx": $$$$$$56,
    "site/sections/Social/InstagramFeed.tsx": $$$$$$57,
    "site/sections/Social/InstagramPosts.tsx": $$$$$$58,
    "site/sections/Social/WhatsApp.tsx": $$$$$$59,
    "site/sections/Theme/Theme.tsx": $$$$$$60,
  },
  "actions": {
    "site/actions/minicart/submit.ts": $$$$$$$$$0,
    "site/actions/newsletter/submit.ts": $$$$$$$$$1,
    "site/actions/wishlist/submit.ts": $$$$$$$$$2,
  },
  "apps": {
    "site/apps/deco/analytics.ts": $$$$$$$$$$$0,
    "site/apps/deco/htmx.ts": $$$$$$$$$$$1,
    "site/apps/deco/konfidency.ts": $$$$$$$$$$$2,
    "site/apps/deco/vtex.ts": $$$$$$$$$$$3,
    "site/apps/site.ts": $$$$$$$$$$$4,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
